name: Relase

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  CheckVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if release branch does not exist
        run: |
          if ! git ls-remote --exit-code --heads origin release/${{ inputs.version }}; then
            echo "Release branch release/${{ inputs.version }} does not exist. Failing."
            exit 1
          fi

  FinilizeRelase:
    runs-on: ubuntu-latest
    needs: CheckVersion
    steps:
      - name: Checkout release branch
        run: |
          git checkout release/${{ inputs.version }}

      - name: Create tag if it does not exist
        run: |
          TAG_NAME=${{ inputs.version }}
          if git rev-parse "refs/tags/$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists."
          else
            git tag --annotate x.y.z --message "Release x.y.z"
            git push --tags
            echo "Tag $TAG_NAME created and pushed."
          fi      
      
