name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true

jobs:
  CheckReleaseBranchExists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Fail if release branch does not exist
        run: |
          if ! git ls-remote --exit-code --heads origin release/${{ inputs.version }}; then
            echo "Release branch release/${{ inputs.version }} does not exist. Failing."
            exit 1
          fi

  FinalizeRelease:
    runs-on: ubuntu-latest
    needs: CheckReleaseBranchExists
    permissions:
      contents: write # Grant write permissions to the GITHUB_TOKEN
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          ref: release/${{ inputs.version }}

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tag if it does not exist
        run: |
          TAG_NAME=${{ inputs.version }}
          if git rev-parse "refs/tags/$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists."
          else
            git tag --annotate "$TAG_NAME" --message "Release $TAG_NAME"
            git push --tags
            echo "Tag $TAG_NAME created and pushed."
          fi      
      
